### PR TITLE
Glader

### PR DESCRIPTION
**Pull request by Glader011235**
Pull request so I can see coveralls

### CODE REVIEW

**Comment by cmshobe** [comment]
screen shot 2018-07-10 at 8 01 04 am

**Comment by Glader011235** [comment]
Katy- the documentation and tests for these models are done. I couldn't quite get to 100% in 2 of the models... I can tell you more tomorrow.

**Comment by kbarnhart** [comment]
@Glader011235 you are correct that those remaining lines were untestable. There is really no reason for them since there is no way that those fields could have existed. So I deleted them.

**Comment by kbarnhart** [comment]
I get one error though. 

for model 400

```
______________________________________________________ test_diffusion_only ______________________________________________________
Traceback (most recent call last):
  File "/Users/barnhark/projects/TerrainBento/terrainbento/tests/test_400.py", line 67, in test_diffusion_only
    steady_z_profile_firsthalf = (steady_domain[0:len(domain)/2])**2*U/(regolith_transport_parameter*2*(1-np.exp(-predicted_depth/soil_transport_decay_depth)))-(U*(number_of_node_columns/2)**2)/(2*regolith_transport_parameter*(1-np.exp(-predicted_depth/soil_transport_decay_depth)))
TypeError: slice indices must be integers or None or have an __index__ method
```

I'll be able to think more about it tomorrow

**Pull request merged**
