### PR TITLE
vsa tests

### PR DESCRIPTION
**Pull request by Glader011235**
aiming for 100% no buggies

### CODE REVIEW

**Comment by Glader011235** [comment]
Basic pure diffusion and pure stream power tests are good to go on models 200, 202, 208, 210- haven't written any VSA specific ones yet, and I held off on model 300 (StVs) yet because I'm not sure how to deal with the St part...

**Comment by kbarnhart** [comment]
@Glader011235 this is awesome!

Also, as a general note, the `self.K` vs `self.K_sp` error you fixed was a new thing that I induced in PR #63 (aka, not old and actually a problem). I tried to find all the places where that was a problem, bt because not everything had precipchanger tests, it was hard... Thank you for finding it!

not surprisingly, we still have 2 windows python 2.7 failures in AppVeyor. That is my fault and I will fix it.

**Comment by kbarnhart** [comment]
Few other thoughts on tests.

1) don't worry about 300 at the moment. 

2) As best as I can tell, the most extensive steady state test that we can do when Aeff is different from A is as follows:

  a) assert that Aeff has been calculated correctly
 
 b) assert that slopes are all consistent with K Aeff**m S**n

 c) we could assert that all slopes are steeper than what we'd calculate with K A**m S**n, but I don' think it would add anything to (a) and (b)

**Comment by Glader011235** [comment]
Ok Katy, I think these are good to go!

**Pull request merged**
