### PR TITLE
fixing (almost) 002 tests

### PR DESCRIPTION
**Pull request by kbarnhart**
Addresses (almost) #60 

@cmshobe @gregtucker take a look?

also, I can't seem to figure out why the one test that is failing is failing... if either of you notice something, let me know.

### CODE REVIEW

**Comment by cmshobe** [comment]
I think your new test looks good; if its the shear stress/threshold test that's failing, I'm pretty sure it's because n != 1. Unfortunately I don't know the guts of that component well enough to go deeper than that.

**Comment by kbarnhart** [comment]
looking at this component in more depth it does appear to not honor a value for n != 1.

**Comment by kbarnhart** [comment]
also @cmshobe I'm somewhat confused by your 008 and 018 tests... how did you come up with the equations for the analytical solutions for no-diffusion end members?

I'm not sure how we'd make such an analytical solution anyways, since the K value is constantly changing as erosion progresses... I suspect this is why the analytical solution notebook is empty. 

I think your tests only work because the threshold value you used is really small....

I think its totally fine if we don't have an analytical solution for things that don't have analytical solutions, but I want to understand your tests since I'm working on 808 right now.

Also, sorry I didn't catch this when I reviewed your PR... as it always happens, its hard to do a really thorough review at the right time...

**Comment by cmshobe** [comment]
@kbarnhart no worries! you're exactly right; they only work because the threshold is really small and the decimal precision of the test is coarse. I think your approach that you used in 002 would work, of making sure the values fall between the two solutions (the hard threshold solution and the no threshold solution). 

Isnt it just the threshold that keeps changing through time, not K? and if you set the thresh change per depth to be 0, the same type of test you made for 002 should work for 008 and 018 as well?

**Comment by kbarnhart** [comment]
These tests will not pass. There should be one 008 and one 002 that don't pass because of the SmoothThresh eroder being set to zero. 

However, I had a really hard time getting the tests to work with thresholds of 0.0000001 (and I don't want to relax the decimal comparison to much because we are dealing with slopes that are already somewhat small). 

This [Landlab PR](https://github.com/landlab/landlab/pull/747) fixes the issue with 002. I don't yet understand why it doesn't fix the issue with 008. 

@cmshobe @gregtucker comments welcome!

**Comment by cmshobe** [comment]
Only had a moment to look at this (it's early morning here) but I, like you, don't have a good intuition for why the 008 test isn't working since the structure seems the same as the 002 test.

**Comment by kbarnhart** [comment]
This should have a few failures related to 008 and 018 (than need landlab to be updated in order to fix). 

If these are the only failures, I'm going to merger.

**Pull request merged**
