### PR TITLE
Cmshobe/add model docs

### PR DESCRIPTION
**Pull request by cmshobe**
adding documentation for models: 002, 008, 010, 018, and 410.
@kbarnhart some CI tests are failing but I am not quite sure why-- mind taking a look at this and merging as long as my documentation hasn't messed up the CI?

### CODE REVIEW

**Comment by kbarnhart** [comment]
00C = 008 + 004 (depth dependent + shear stress)

so documentation for 008 needs to acknowledged that it is the model _program_ to use for models 008 and 00C.

model 000 has example for this. 

does that help?

**Comment by cmshobe** [comment]
Yaaa thanks!

**Comment by cmshobe** [comment]
I found what was causing the CI problems-- no 'F_f' parameter in the docstring tests of some of the erosionDeposition-related models. Should be fixed now.

**Comment by kbarnhart** [comment]
Also, I wouldn't worry about the two failed CI tests. 

AND!!!! This PR would bring us over 50% coverage! wooo!

**Comment by cmshobe** [comment]
@kbarnhart models 002, 008, 010, 018, and 410 are at 100%! I am off to Germany, but keep me updated and I can do more stuff when I get back on 7/23 if needed.

**Comment by kbarnhart** [comment]
Thanks for doing this and for estimating the time it took you!
Merging!

**Pull request merged**
