### PR TITLE
Support developer install with current Python and Landlab versions

### PR DESCRIPTION
**Pull request by mdpiper**
This PR represents the minimum* amount of change to get a developer version of Terrainbento to install and run with current versions of Python (3.12) and Landlab (2.8). Mostly, this means removing *versioneer* in favor of *zest.releaser*. In order to get the tests to pass, though, I also made a pair of changes that might need more discussion. They are:

1. 9007fadfbec5aa6750e1c306014554ac292041fd: Set a small positive value for soil weathering rate in a couple of the tests. See also https://github.com/landlab/landlab/issues/1951.
1. e51bebd4f47de469542b4485806178c383b4531f: Added a few extra digits to a value in a truth file.

*Or close. There are also some other updates I'd like to apply, but I'll open issues on them first.

### CODE REVIEW

**Comment by kbarnhart** [comment]
@mdpiper Thanks for doing this. :tada: I don't see any issues with the changes you've made.

**Comment by mdpiper** [comment]
@kbarnhart Awesome, thanks!

**Comment by mdpiper** [comment]
@kbarnhart Would you be OK merging these changes? We have a summer student at CSDMS who would like to add a new terrainbento component, but she's building off of my fork & branch.

**Comment by kbarnhart** [comment]
@mdpiper thanks for the ping, merged.

**Comment by kbarnhart** [comment]
@mdpiper also, I made you a maintainer, since you are working on this actively.

**Comment by mdpiper** [comment]
@kbarnhart Thanks for merging this PR. I didn't want to bug you, but it'll be helpful for the student.

I'll use my new powers judiciously!

**Comment by kbarnhart** [comment]
Glad someone is finding this repo useful! Hope the work goes well!

**Pull request merged**
